return {
  "nvimdev/dashboard-nvim",
  event = "VimEnter",
  config = function()
    require("dashboard").setup({
      theme = "doom",
      config = {
        header = {
          "                                 ",
          "                                 ",
          "                                 ",
          "                 ▄ ▄             ",
          "       ▄   ▄▄▄     ▄ ▄▄▄ ▄ ▄     ",
          "       █ ▄ █▄█ ▄▄▄ █ █▄█ █ █     ",
          "    ▄▄ █▄█▄▄▄█ █▄█▄█▄▄█▄▄█ █     ",
          "  ▄ █▄▄█ ▄ ▄▄ ▄█ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄  ",
          "  █▄▄▄▄ ▄▄▄ █ ▄ ▄▄▄ ▄ ▄▄▄ ▄ ▄ █ ▄",
          "▄ █ █▄█ █▄█ █ █ █▄█ █ █▄█ ▄▄▄ █ █",
          "█▄█ ▄ █▄▄█▄▄█ █ ▄▄█ █ ▄ █ █▄█▄█ █",
          "    █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█ █▄█▄▄▄█    ",
          "                                 ",
          "                                 ",
          "                                 ",
          "                                 ",
          "                                 ",
        },
        center = {
          {
            icon = "  ",
            icon_hi = "Title",
            desc = "Find file                           ",
            desc_hi = "String",
            key = "ff",
            keymap = "SPC f f",
            action = "LazyVim.pick()",
          },
          {
            icon = "  ",
            icon_hi = "Title",
            desc = "New file                            ",
            desc_hi = "String",
            key = "fn",
            keymap = "SPC f n",
            aciton = "ene | startinsert",
          },
          {
            icon = "  ",
            icon_hi = "Title",
            desc = "Recent files                        ",
            desc_hi = "String",
            key = "fr",
            keymap = "SPC f r",
            action = "LazyVim.pick('oldfiles')",
          },
          {
            icon = "  ",
            icon_hi = "Title",
            desc = "Find text                           ",
            desc_hi = "String",
            key = "fr",
            keymap = "SPC f r",
            action = "LazyVim.pick('oldfiles')",
          },
        },
        footer = { "hekatonkheirex's neovim config" },
      },
    })
  end,
  dependencies = { { "nvim-tree/nvim-web-devicons" } },
}
